name: DreamingWorld
main: net.dreamingworld.DreamingWorld
version: 0.1 alpha 1
authors: [Konstantin Tolstoy, Stepan Gaidukevich]
website: dreamingworld.net

commands:
  dwgive:
    description: Gives DreamingWorld item to player
    permission: dreamingworld.give
    aliases: [dwg]
    usage: /<command> <player> <item> [amount]