name: DreamingWorld
main: net.dreamingworld.DreamingWorld
version: 0.1 pre-alpha
authors: [Konstantin Tolstoy, Stepan Gaidukevich]
website: dreamingworld.net

commands:
  dwgive:
    description: Gives DreamingWorld item to player
    permission: dreamingworld.give
    aliases: [dwg]
    usage: /<command> <player> <item> [amount]
  dwsummon:
    description: Summons DreamingWorld entity at player's position
    permission: dreamingworld.summon
    aliases: [dws]
    usage: /<command> <player> <mob>