name: DreamingWorld
main: net.dreamingworld.DreamingWorld
version: 0.1
authors: [Konstantin Tolstoy, Stepan Gaidukevich]
website: dreamingworld.net

commands:
  channel:
    description: Changes chat channel
    permission: dreamingworld.channel
    aliases: [ch, chat, chatchannel, cc]
    usage: /<command> <global|local>

  tell:
    description: Sends private message to specified player
    permission: dreamingworld.tell
    aliases: [msg, w]
    usage: /<command> <player> <message...>

  global:
    description: Sends message to global chat instantly
    permission: dreamingworld.instantmessage
    aliases: [gl, nl, notlocal]
    usage: /<command> <message...>

  local:
    description: Sends message to local chat instantly
    permission: dreamingworld.instantmessage
    aliases: [l]
    usage: /<command> <message...>

  reply:
    description: Sends reply to last direct message
    permission: dreamingworld.reply
    aliases: [r]
    usage: /<command> <message...>


  teleport:
    description: Teleportation request command
    permission: dreamingworld.teleport
    aliases: [tp, tpa]
    usage: /<command> <player>

  teleportaccept:
    description: Accepts teleportation request
    permission: dreamingworld.teleportaccept
    aliases: [tpaccept]
    usage: /<command> [player]

  teleportdeny:
    description: Denies teleportation request
    permission: dreamingworld.teleportdeny
    aliases: [tpdeny]
    usage: /<command> [player]

  spawn:
    description: Teleports player to spawn
    permission: dreamingworld.teleport
    usage: /<command>


  rank:
    description: Rank management
    permission: dreamingworld.rank
    aliases: [rn, rk, rnk, perm, perms, permissions]
    usage: /<command> <player> <rank>


  dwgive:
    description: Gives DreamingWorld item to player
    permission: dreamingworld.give
    aliases: [dwg]
    usage: /<command> <player> <item> [amount]

  dwsummon:
    description: Summons DreamingWorld entity at player's position
    permission: dreamingworld.summon
    aliases: [dws]
    usage: /<command> <player> <mob>

  dwstructure:
    description: Generates structure at player's target
    permission: dreamingworld.structure
    aliases: [dwstruct, dwstr]
    usage: /<command> <structure>

  dwresearch:
    description: Gives research to player
    permission: dreamingworld.research
    aliases: [dwr]
    usage: /<command> <player> <research>

  systeminfo:
    description: Shows server status
    permission: dreamingworld.systeminfo
    aliases: [sysinfo, si, servhealth, health]
    usage: /<command>


  recipes:
    description: Shows recipe book
    permission: dreamingworld.recipes
    aliases: [recipebook, rb, crafts]
    usage: /<command>


  guild:
    description: Guild management
    permission: dreamingworld.guilds
    usage: Type /guild help for info
    aliases: [g]


permissions:
  dreamingworld.chat.*:
    children:
      dreamingworld.channel: true
      dreamingworld.tell: true
      dreamingworld.instantmessage: true

  dreamingworld.debug.*:
    children:
      dreamingworld.give: true
      dreamingworld.summon: true
      dreamingworld.structure: true
      dreamingworld.research: true
      dreamingworld.systeminfo: true

  dreamingworld.gameplay.*:
    children:
      dreamingworld.teleport: true
      dreamingworld.teleportaccept: true
      dreamingworld.teleportdeny: true
      dreamingworld.recipes: true
      dreamingworld.guilds: true


  # Chat
  dreamingworld.channel:
    default: true
  dreamingworld.tell:
    default: true
  dreamingworld.instantmessage:
    default: true

  # Gameplay
  # Teleportation
  dreamingworld.teleport:
    default: true
  dreamingworld.teleportaccept:
    default: true
  dreamingworld.teleportdeny:
    default: true
  # Other
  dreamingworld.recipes:
    default: true
  dreamingworld.guilds:
    default: true

  # Shit
  dreamingworld.rank:
    default: op

  # Debug
  dreamingworld.give:
    default: op
  dreamingworld.summon:
    default: op
  dreamingworld.structure:
    default: op
  dreamingworld.research:
    default: op
  dreamingworld.systeminfo:
    default: op